# Default values for activiti-cloud-platform-quickstart in Jenkins-X.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ## Configure pull secrets for all deployments
  registryPullSecrets: []

  # Use Yaml formatted string to add extra environment properties to all deployments, i.e.
  extraEnv: |
    - name: SERVER_USEFORWARDHEADERS
      value: "true"
    - name: SERVER_TOMCAT_INTERNALPROXIES
      value: ".*"
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "*"
    
  keycloak:
    ## Configure Activiti Keycloak host template, i.e. "activiti-keycloak.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    # if not set, keycloak deployment is automatically exposed on gaetway host, 
    # i.e. {{ template \"common.gateway-host\" . }}
    host: ""

    ## Set full url to configure external Keycloak, https://my.keycloak.com/auth
    # if not set, keycloak deployment is automatically exposed on gaetway host, 
    # i.e. http(s)://{{ template \"common.gateway-host\" . }}/auth
    url: ""

    ## Configure Keycloak realm
    realm: "activiti"
    resource: "activiti"
    client: "activiti"
    
    ## Use Yaml formatted string to add keycloak properties to deployments, i.e.
    extraEnv: |
      # - name: KEYCLOAK_USERESOURCEROLEMAPPINGS
      #   value: "false"

  gateway:
    ## Set to configure single domain name for all services, i.e. "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ .Values.global.gateway.domain }}"
    host: "activiti-cloud-gateway.{{ .Release.Namespace }}.{{ template \"common.gateway-domain\" . }}"

    ## Set to false enables HTTPS configuration on all urls 
    http: "true"
    
    ## Set to true to enable automatic TLS for ingress if https is enabled
    tlsacme: "false"    

    ## Set domain name to expose service ingresses via gateway.host and keycloak.host
    domain: "REPLACEME"

    ## Configure global annotations for all service ingresses, i.e. Let's Encrypt certificate issuer
    annotations: 
      certmanager.k8s.io/issuer: letsencrypt-prod
      
activiti-cloud-modeling:
  enabled: true
  service:
    name: activiti-cloud-modeling
  ingress:
    ## Enable Activiti Modeler Ingress if not using Activiti Gateway  
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
    frontend:
      annotations: {}
    backend:
      annotations: {}
      
application:
  runtime-bundle:
    service: 
      name: rb-my-app  
    enabled: false
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-query:
    enabled: true
    service: 
      name: query  
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-connector:
    enabled: false
    service: 
      name: example-cloud-connector  

  activiti-cloud-notifications-graphql:
    enabled: true
    service: 
      name: activiti-cloud-notifications  

  activiti-cloud-audit:
    enabled: true
    service: 
      name: audit  
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

infrastructure:
  activiti-keycloak:
    enabled: true
    ingress:
      enabled: true
    keycloak:
      enabled: true
      keycloak:
        preStartScript: |
          /opt/jboss/keycloak/bin/add-user.sh -u admin -p admin
          /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin
          cp /realm/activiti-realm.json .
          sed -i 's/placeholder.com/*/g' activiti-realm.json
  
  activiti-cloud-gateway:
    service:
      name: activiti-cloud-gateway
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "*"
        nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
